[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "dependencies"]
test = "test"
cache_path = "cache"
force = false
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 3

# Test configuration
[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# CI configuration
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# Gas reporting
[profile.default.gas_reports]
# Contract patterns to report gas for
"*" = true

# RPC endpoints
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

# Etherscan API keys
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

[dependencies]
forge-std = "1.10.0"
